### ISSUE TITLE
Establish Workflow

### ISSUE THREAD

**Issue by muelldlr** [DLR-SC/corpus-annotation-graph-builder#28]
As @hecking suggested, a kind of workflow should be established so that people joining a project can get a better start and also support ongoing development.
Broken down, the workflow should map the following tasks:
1.  **Project start**: there should be a basic framework to start with
2. **Ongoing Project Development**: In the course of PRs, additional information should be made available to reviewers so that they can better check that the code doesn't break anything (such as unintentionally/intentionally changing the graph structure or the collections).

**Comment by muelldlr** [comment]
I have simplified the process to get started with CAG. The command `cag start-project` will create a basic framework including a venv. Could you at times test this and see if it is so user-friendly? See branch [https://github.com/DLR-SC/corpus-annotation-graph-builder/tree/28-establish-workflow](https://github.com/DLR-SC/corpus-annotation-graph-builder/tree/28-establish-workflow)

**Comment by muelldlr** [comment]
Regarding "**Ongoing Project Development**" #24  should be enough for a reviewer to get an overview of what has been changed. Or how do you see that? @roxanneelbaff

**Comment by roxanneelbaff** [comment]
Thank you @muelldlr ! I am excited to see the changes - Will do that on Friday and let you know!
