### ISSUE TITLE
Constant NODE and Edge NAMES definitions partially incorrect

### ISSUE THREAD

**Issue by muelldlr** [DLR-SC/corpus-annotation-graph-builder#7]
As defined in `GraphCreatorBase` the name of the Node needs to be ` _ABSTRACT_NODE_NAME = 'Abstract'`. But in `nodes.py` it is defined as `AbstractNode`.

The solution is to rename `class AbstractNode(GenericOOSNode):` to `class Abstract(GenericOOSNode):`

**Edit:** Same applies to `_EDGE_ABSTRACT_TEXT = 'AbstractText'`. This edge is not defined in `relations.py`

Or do you see any negative side effect by renaming this class @roxanneelbaff ?

**Comment by roxanneelbaff** [comment]
Change the name in the base instead of the class name
